### ISSUE TITLE
ADD pages "Product list" and "Product details"

### ISSUE THREAD

**Issue by Andres-Fernandez-Caballero** [Andres-Fernandez-Caballero/audaces-react-app#4]
### Se agregan al proyecto las paginas de lista de productos y detalle de producto
Estas paginas serán provisoriamente maquetas hasta que se pueda implementar la funcionalidad de peticiones al backend correctamente

**Comment by rodripavon97** [comment]
Ahi abro de nuevo, se crea de nuevo el branch

**Comment by Andres-Fernandez-Caballero** [comment]
Componentes creados con exito se cierra la issue
